/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 使用用户名和密码登录。成功后：
         *     - 返回 Access Token（JSON body，前端存内存）
         *     - 通过 Set-Cookie 设置 Refresh Token（HttpOnly + Secure + SameSite=Lax）
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 Access Token
         * @description 使用 Cookie 中的 Refresh Token 获取新的 Access Token。浏览器客户端必须使用 `credentials: include`，不应手动设置 HttpOnly Cookie。
         *     采用 Token 轮换：每次刷新吊销旧 Refresh Token，签发新的。
         *     若旧 Token 被重复使用（重放攻击），吊销该用户所有 Refresh Token。
         */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 吊销当前 Refresh Token 并清除 Cookie
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文章列表
         * @description 分页获取已发布文章列表，支持分类、标签、搜索筛选
         */
        get: operations["listArticles"];
        put?: never;
        /**
         * 创建文章
         * @description 创建新文章（默认草稿状态）
         */
        post: operations["createArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文章归档
         * @description 按年份-月份分组返回所有已发布文章
         */
        get: operations["listArticleArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文章详情
         * @description 根据 slug 获取文章详情（含 Markdown 正文），同时浏览量 +1
         */
        get: operations["getArticle"];
        /** 更新文章 */
        put: operations["updateArticle"];
        post?: never;
        /** 删除文章 */
        delete: operations["deleteArticle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发布文章
         * @description 将草稿状态的文章发布，设置 published_at
         */
        post: operations["publishArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消发布（转为草稿） */
        post: operations["unpublishArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置/取消置顶 */
        post: operations["setArticleTop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取项目列表
         * @description 获取所有 active 状态的项目，支持精选筛选
         */
        get: operations["listProjects"];
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取项目详情 */
        get: operations["getProject"];
        /** 更新项目 */
        put: operations["updateProject"];
        post?: never;
        /** 删除项目 */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有分类 */
        get: operations["listCategories"];
        put?: never;
        /** 创建分类 */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取分类详情 */
        get: operations["getCategory"];
        /** 更新分类 */
        put: operations["updateCategory"];
        post?: never;
        /**
         * 删除分类
         * @description 该分类下有文章时拒绝删除（需先迁移文章）
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有标签 */
        get: operations["listTags"];
        put?: never;
        /** 创建标签 */
        post: operations["createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取标签详情 */
        get: operations["getTag"];
        /** 更新标签 */
        put: operations["updateTag"];
        post?: never;
        /** 删除标签 */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取文章评论列表
         * @description 获取已审核通过的评论，树形结构（最多两层：一级评论 + 回复）。
         *     基于签名访客 ID Cookie 识别用户。
         */
        get: operations["listArticleComments"];
        put?: never;
        /**
         * 发表评论
         * @description 匿名发表评论，默认 pending 状态。
         *     包含 Honeypot 隐藏字段（website_url，正常用户不会填写）。
         *     限制：内容 ≤2000 字，链接数 ≤3，每访客 10 条/小时。
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除评论 */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台获取评论列表 */
        get: operations["listAdminComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/comments/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 审核通过评论 */
        post: operations["approveComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/comments/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝评论 */
        post: operations["rejectComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 点赞/取消点赞（幂等）
         * @description 幂等操作：根据 action 字段点赞或取消点赞。
         *     基于签名访客 ID Cookie 去重。重复点赞不报错，返回当前状态。
         *     限流：每访客 30 次/小时。
         */
        put: operations["setArticleLike"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{slug}/like/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取点赞状态
         * @description 查询当前访客是否已点赞及点赞总数
         */
        get: operations["getArticleLikeStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台数据概览 */
        get: operations["getAdminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台获取文章列表（含草稿） */
        get: operations["listAdminArticles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 后台获取项目列表（含已归档） */
        get: operations["listAdminProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/site/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取站点设置（公开） */
        get: operations["getSiteSettings"];
        /** 更新站点设置 */
        put: operations["updateSiteSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/site/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取公开统计数据
         * @description 首页展示用的统计数据（文章总数、项目总数等）
         */
        get: operations["getSiteStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rss.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 RSS */
        get: operations["getRss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sitemap.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Sitemap */
        get: operations["getSitemap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/upload/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传图片
         * @description 上传文章/项目配图。安全措施：
         *     - 服务端 MIME 类型检测（不相信扩展名）
         *     - 随机文件名（UUID），禁止用户控制路径
         *     - 图片重新编码（去除元数据，防止恶意文件）
         *     - 最大 5MB，支持 jpg/png/webp/gif
         */
        post: operations["uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活检查
         * @description 仅检查进程是否存活，不依赖外部服务。用于 Docker healthcheck 和负载均衡。
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪检查
         * @description 检查数据库连接是否正常。用于部署后流量切入前的就绪探测。
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /**
             * @description 状态码，0 表示成功
             * @example 0
             */
            code: number;
            /** @example success */
            message: string;
            /** @description 响应数据（任意类型） */
            data?: unknown;
        };
        ErrorResponse: {
            /** @example 40001 */
            code: number;
            /** @example 参数校验失败 */
            message: string;
            /** @description 附加错误详情（如字段级校验错误） */
            data?: Record<string, never> | null;
        };
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 10 */
            page_size: number;
            /** @example 100 */
            total: number;
            /** @example 10 */
            total_pages: number;
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /** Format: password */
            password: string;
        };
        AccessToken: {
            /** @description JWT Access Token（15分钟有效，前端存内存） */
            access_token: string;
            /** @example Bearer */
            token_type: string;
            /**
             * @description 有效期（秒）
             * @example 900
             */
            expires_in: number;
        };
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            nickname: string;
            email: string | null;
            avatar_url: string | null;
            bio: string | null;
            /** @enum {string} */
            role: "admin" | "editor";
            /** Format: date-time */
            created_at: string;
        };
        Article: {
            /** Format: int64 */
            id: number;
            slug: string;
            title: string;
            summary: string;
            cover_image: string | null;
            category: components["schemas"]["Category"] | null;
            tags: components["schemas"]["Tag"][];
            author: components["schemas"]["User"];
            /** @enum {string} */
            status: "draft" | "published" | "archived";
            is_top: boolean;
            view_count: number;
            like_count: number;
            comment_count: number;
            /** Format: date-time */
            published_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ArticleDetail: components["schemas"]["Article"] & {
            /** @description Markdown 正文 */
            content: string;
        };
        ArticleCreateRequest: {
            title: string;
            /** @description 不填则自动从标题生成 */
            slug?: string;
            /** @description 不填则自动截取正文 */
            summary?: string;
            content: string;
            cover_image?: string | null;
            /** Format: int64 */
            category_id?: number | null;
            tag_ids?: number[];
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "published";
            /** @default false */
            is_top: boolean;
        };
        ArticleUpdateRequest: {
            title?: string;
            slug?: string;
            summary?: string;
            content?: string;
            cover_image?: string | null;
            /** Format: int64 */
            category_id?: number | null;
            tag_ids?: number[];
            is_top?: boolean;
        };
        ArticleListResponse: {
            items: components["schemas"]["Article"][];
            pagination: components["schemas"]["Pagination"];
        };
        ArchiveGroup: {
            /** @example 2026 */
            year: number;
            months: {
                /** @example 8 */
                month: number;
                articles: {
                    slug: string;
                    title: string;
                    /** Format: date-time */
                    published_at: string;
                }[];
            }[];
        };
        Project: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            summary: string;
            cover_image: string | null;
            /**
             * @description 技术栈列表
             * @example [
             *       "Go",
             *       "React",
             *       "Docker"
             *     ]
             */
            technologies: string[];
            /** Format: uri */
            repository_url: string | null;
            /** Format: uri */
            demo_url: string | null;
            featured: boolean;
            sort_order: number;
            /** @enum {string} */
            status: "active" | "archived";
            /** Format: date */
            started_at: string | null;
            /** Format: date */
            completed_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProjectDetail: components["schemas"]["Project"] & {
            /** @description Markdown 详细描述 */
            content: string;
        };
        ProjectCreateRequest: {
            name: string;
            /** @description 不填则自动生成 */
            slug?: string;
            summary?: string;
            /** @description Markdown 详细描述 */
            content?: string;
            cover_image?: string | null;
            technologies?: string[];
            /** Format: uri */
            repository_url?: string | null;
            /** Format: uri */
            demo_url?: string | null;
            /** @default false */
            featured: boolean;
            /** @default 0 */
            sort_order: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "archived";
            /** Format: date */
            started_at?: string | null;
            /** Format: date */
            completed_at?: string | null;
        };
        ProjectUpdateRequest: {
            name?: string;
            slug?: string;
            summary?: string;
            content?: string;
            cover_image?: string | null;
            technologies?: string[];
            /** Format: uri */
            repository_url?: string | null;
            /** Format: uri */
            demo_url?: string | null;
            featured?: boolean;
            sort_order?: number;
            /** @enum {string} */
            status?: "active" | "archived";
            /** Format: date */
            started_at?: string | null;
            /** Format: date */
            completed_at?: string | null;
        };
        ProjectListResponse: {
            items: components["schemas"]["Project"][];
            pagination: components["schemas"]["Pagination"];
        };
        Category: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            description: string | null;
            /** Format: int64 */
            parent_id: number | null;
            icon: string | null;
            sort_order: number;
            /** @description 该分类下已发布文章数 */
            article_count: number;
            /** Format: date-time */
            created_at: string;
        };
        CategoryRequest: {
            name: string;
            /** @description 不填则自动生成 */
            slug?: string;
            description?: string;
            /** Format: int64 */
            parent_id?: number | null;
            icon?: string;
            /** @default 0 */
            sort_order: number;
        };
        Tag: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            /**
             * @description 十六进制颜色
             * @example #3B82F6
             */
            color: string | null;
            article_count: number;
            /** Format: date-time */
            created_at: string;
        };
        TagRequest: {
            name: string;
            slug?: string;
            /** @example #3B82F6 */
            color?: string;
        };
        Comment: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            article_id?: number;
            /**
             * Format: int64
             * @description 父评论 ID（回复时填写，最多两层）
             */
            parent_id?: number | null;
            nickname?: string;
            website?: string | null;
            /** @description 已清洗的评论内容 */
            content?: string;
            /** @enum {string} */
            status?: "pending" | "approved" | "rejected";
            /** Format: date-time */
            created_at?: string;
        };
        CommentNode: components["schemas"]["Comment"] & {
            /** @description 回复列表（第二层，不再递归） */
            replies?: components["schemas"]["Comment"][];
        };
        CommentCreateRequest: {
            nickname: string;
            /**
             * Format: email
             * @description 不公开，用于回复通知
             */
            email?: string;
            website?: string | null;
            /** @description 评论内容（纯文本或受限 Markdown，存储前清洗） */
            content: string;
            /**
             * Format: int64
             * @description 回复的父评论 ID（必须是一级评论）
             */
            parent_id?: number | null;
            /** @description Honeypot 隐藏字段，正常用户留空。填写则视为垃圾评论。 */
            website_url?: string | null;
        };
        CommentListResponse: {
            /** @description 一级评论列表，每个包含 replies */
            items: components["schemas"]["CommentNode"][];
            pagination: components["schemas"]["Pagination"];
        };
        LikeStatus: {
            /** @description 点赞总数 */
            like_count: number;
            /** @description 当前访客是否已点赞 */
            liked: boolean;
        };
        LikeRequest: {
            /**
             * @description 点赞或取消
             * @enum {string}
             */
            action: "like" | "unlike";
        };
        DashboardStats: {
            total_articles?: number;
            published_articles?: number;
            draft_articles?: number;
            total_projects?: number;
            total_views?: number;
            total_likes?: number;
            total_comments?: number;
            pending_comments?: number;
            total_categories?: number;
            total_tags?: number;
            recent_articles?: {
                id?: number;
                title?: string;
                slug?: string;
                status?: string;
                /** Format: date-time */
                published_at?: string;
            }[];
            popular_articles?: {
                id?: number;
                title?: string;
                slug?: string;
                view_count?: number;
            }[];
        };
        PublicStats: {
            /** @description 已发布文章数 */
            total_articles: number;
            /** @description active 项目数 */
            total_projects: number;
            total_categories: number;
            total_tags: number;
        };
        SiteSettings: {
            /** @example 我的技术博客 */
            site_title: string;
            /** @example 分享计算机技术与生活感悟 */
            site_description: string;
            site_keywords: string;
            footer_text: string;
            icp_number: string | null;
            /** @description 关于页内容（Markdown） */
            about_content: string;
            social_links: {
                /** @example GitHub */
                name: string;
                /**
                 * Format: uri
                 * @example https://github.com/yourname
                 */
                url: string;
                icon: string;
            }[];
        };
    };
    responses: {
        /** @description 操作成功 */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponse"];
            };
        };
        /** @description 请求参数错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证或 Token 过期 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 无权限（角色不足） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源冲突（重复创建/状态不允许） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求过于频繁（限流） */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 页码（从 1 开始） */
        PageParam: number;
        /** @description 每页数量 */
        PageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    /** @description Refresh Token Cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AccessToken"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    /** @description 新的 Refresh Token Cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["AccessToken"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功并清除 Refresh Token Cookie */
            200: {
                headers: {
                    /** @description 使 refresh_token 立即过期的 Cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listArticles: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
                /** @description 分类 slug */
                category?: string;
                /** @description 标签 slug */
                tag?: string;
                /** @description 搜索关键词 */
                keyword?: string;
                /** @description 排序方式 */
                sort?: "newest" | "hottest" | "views";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文章列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ArticleListResponse"];
                    };
                };
            };
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Article"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listArticleArchive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 归档数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ArchiveGroup"][];
                    };
                };
            };
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文章详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ArticleDetail"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Article"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Article"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    unpublishArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setArticleTop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    is_top: boolean;
                };
            };
        };
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
                /** @description 仅返回精选项目 */
                featured?: boolean;
                /** @description 按技术栈筛选 */
                technology?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ProjectListResponse"];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Project"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ProjectDetail"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Project"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分类列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分类详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Category"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 标签列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Tag"][];
                    };
                };
            };
        };
    };
    createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Tag"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 标签详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Tag"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Tag"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listArticleComments: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评论列表（树形） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["CommentListResponse"];
                    };
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description 评论提交成功（待审核） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["Comment"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAdminComments: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
                status?: "pending" | "approved" | "rejected" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 评论列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["CommentListResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approveComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setArticleLike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikeRequest"];
            };
        };
        responses: {
            /** @description 操作成功，返回当前点赞状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["LikeStatus"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getArticleLikeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 点赞状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["LikeStatus"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAdminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统计数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["DashboardStats"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminArticles: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
                status?: "draft" | "published" | "archived" | "all";
                keyword?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文章列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ArticleListResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listAdminProjects: {
        parameters: {
            query?: {
                /** @description 页码（从 1 开始） */
                page?: components["parameters"]["PageParam"];
                /** @description 每页数量 */
                page_size?: components["parameters"]["PageSizeParam"];
                status?: "active" | "archived" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["ProjectListResponse"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSiteSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 站点设置 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["SiteSettings"];
                    };
                };
            };
        };
    };
    updateSiteSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteSettings"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSiteStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统计数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: components["schemas"]["PublicStats"];
                    };
                };
            };
        };
    };
    getRss: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RSS 2.0 XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": string;
                };
            };
        };
    };
    getSitemap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sitemap XML */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
        };
    };
    uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 图片文件
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 上传成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"] & {
                        data?: {
                            /**
                             * Format: uri
                             * @description 图片访问 URL
                             */
                            url?: string;
                            filename?: string;
                            /** @description 文件大小（字节） */
                            size?: number;
                            width?: number;
                            height?: number;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 文件过大（超过 5MB） */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ready */
                        status?: string;
                        /** @example connected */
                        database?: string;
                    };
                };
            };
            /** @description 服务未就绪（数据库不可用） */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example not_ready */
                        status?: string;
                        /** @example disconnected */
                        database?: string;
                    };
                };
            };
        };
    };
}
